swagger: "2.0"
info:
  version: "2024-06-18T04:59:36Z"
  title: "ProductListApi"
host: "m1xge546pb.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
  - "https"
paths:
  /products:
    get:
      responses:
        '200':
          description: "A list of products"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "ID of product"
                  example: 1
                title:
                  type: string
                  description: "Product name"
                  "example": "Iphone 14"
                price:
                  type: integer
                  description: "Product price"
                  example: 100


  /products/{product_id}:
    get:
      parameters:
        - name: "product_id"
          in: "path"
          required: true
          type: "string"
      responses:
        '200':
          description: "Product returned by id"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "ID of product"
                example: 1
              title:
                type: string
                description: "Product name"
                "example": "Iphone 14"
              price:
                type: integer
                description: "Product price"
                example: 100

